Sat 01 Mar 2025 08:56:00 AM WET

diff --git a/home/bin/duck b/home/bin/duck
--- a/home/bin/duck
+++ b/home/bin/duck
@@ -1,7 +1,18 @@
 #!/bin/bash
-
 # shellcheck disable=SC1090
-. ~/.duckdns # export DUCKDNS_TOKEN="..."
+# Updates dns name on duckdns.org
+
+if ! test -f ~/.duckdns; then
+	exit 0
+fi
+
+. ~/.duckdns >/dev/null # export
+
+if test -z "$DUCKDNS_TOKEN"; then
+	echo "Invalid ~/.duckdns file format" >&2
+	echo "export DUCKDNS_TOKEN=\"...\"" >&2
+	exit 1
+fi
 
 domains=(
 	"brenopacheco"
