Sat Nov 25 06:30:09 PM WET 2023

diff --git a/files/home/bin/dmenu_pass b/files/home/bin/dmenu_pass
--- a/files/home/bin/dmenu_pass
+++ b/files/home/bin/dmenu_pass
@@ -28,12 +28,18 @@ echo "$password"
 [[ -n $password ]] || exit
 
 if [[ $password == otp:* ]]; then
-	pass otp code -c "$password" 2>/dev/null
+	if ! pass otp code -c "$password"; then
+		notify-send -a pass -t 10000 -i error "Error" "Could not decrypt password"
+		exit 1
+	fi
 	icon="/usr/share/icons/Papirus-Dark/24x24/actions/password-copy.svg"
 	name="${password#*/}"
 	name="${name^}"
 	echo "$name"
 	notify-send -a pass -t 60000 -i "$icon" "${name}" "$(xclip -o -selection 'clipboard')"
 else
-	pass show -c "$password" 2>/dev/null
+	if ! pass show -c "$password"; then
+		notify-send -a pass -t 10000 -i error "Error" "Could not decrypt password"
+		exit 1
+	fi
 fi
