Fri 27 Sep 2024 03:03:16 PM WEST

diff --git a/files/home/bin/sketch b/files/home/bin/sketch
--- a/files/home/bin/sketch
+++ b/files/home/bin/sketch
@@ -4,7 +4,7 @@ LANG=$1
 
 function help() {
 	cat <<EOF
-Usage: sketch [ml|d|go|js|ts|bun|sh|c|lua|rust|zig] [NAME]
+Usage: sketch [ml|d|go|js|ts|bun|sh|c|lua|rust|zig|perl] [NAME]
 
 Creates a sketch project for a given language.
 The directory is created in $HOME/sketch with a random name.
@@ -21,17 +21,17 @@ fi
 LANG=$1
 NAME=$2
 
-if [[ ! "$LANG" =~ ^(ml|d|go|js|ts|bun|sh|c|lua|rust|zig)$ ]]; then
+if [[ ! "$LANG" =~ ^(ml|d|go|js|ts|bun|sh|c|lua|rust|zig|perl)$ ]]; then
 	help
-	echo "Invalid LANG: use ml, d, go, js, ts, bun, c, lua, rust or zig" >&2
+	echo "Invalid LANG: use ml, d, go, js, ts, bun, c, lua, rust, zig or perl" >&2
 	exit 1
 fi
 
 mkdir -p ~/sketch
 
-TMPNAME="$LANG_$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 10)"
+TMPNAME="${LANG}_$(tr -cd 'a-f0-9' < /dev/urandom | head -c 10)"
 
-if [[ ! -z "$NAME" ]]; then
+if [[ -n "$NAME" ]]; then
 	TMPNAME="$NAME-$TMPNAME"
 fi
 
@@ -41,52 +41,10 @@ cat <<EOF
 Setting up sketch project with $LANG in $DIR
 EOF
 
-mkdir -p $DIR
-cd $DIR
+mkdir -p "$DIR"
+cd "$DIR" || exit 1
 git init
 
-echo "$GO_TEMPLATE"
-
-CMAKE_MAKEFILE=$(
-	cat <<'END_HEREDOC'
-.ONESHELL:
-.PHONY: help
-
-BUILD_DIR = cmake
-BIN = main
-
-all: $(BIN)
-	$(BUILD_DIR)/$(BIN)
-
-$(BIN): $(BUILD_DIR)
-	cmake --build $(BUILD_DIR)
-
-$(BUILD_DIR):
-	cmake . -B $(BUILD_DIR) -G Ninja
-
-build: $(BIN)
-
-clean:
-	rm -rf $(BUILD_DIR)
-
-help:
-	@echo "Available targets:"
-	@echo "  all      : Build using cmake and run"
-	@echo "  build  : Builds using cmake"
-	@echo "  clean    : Remove the build directory"
-	@echo "  help     : Show this help message"
-END_HEREDOC
-)
-
-CMAKE_LISTS=$(
-	cat <<'END_HEREDOC'
-cmake_minimum_required(VERSION 3.5 FATAL_ERROR)
-
-project(example LANGUAGES C)
-
-add_executable(main main.c)
-END_HEREDOC
-)
 
 D_TEMPLATE=$(
 	cat <<'END_HEREDOC'
@@ -118,7 +76,7 @@ case $LANG in
 	touch main.go
 	echo -e "package main\n\nfunc main() {\n\n\n}" >main.go
 	echo -e 'all:\n\tgo run main.go' >Makefile
-	cp $IGNORE_DIR/Go.gitignore .gitignore
+	cp "${IGNORE_DIR}/Go.gitignore" .gitignore
 	;;
 "c")
 	echo -e "#include <stdio.h>\n\nint main() {\n\n  return 0;\n}" >main.c
@@ -128,23 +86,23 @@ case $LANG in
 	npm init -y
 	touch main.js
 	echo -e 'all:\n\tnode main.js' >Makefile
-	echo $JS_TSCONFIG >tsconfig.json
+	echo "$JS_TSCONFIG" >tsconfig.json
 	npm i -D typescript @types/node
-	cp $IGNORE_DIR/Node.gitignore .gitignore
+	cp "${IGNORE_DIR}/Node.gitignore" .gitignore
 	;;
 "ts")
 	npm init -y
 	touch main.ts
 	echo -e 'all:\n\tts-node main.ts' >Makefile
 	tsc --init
-	cp $IGNORE_DIR/Node.gitignore .gitignore
+	cp "${IGNORE_DIR}/Node.gitignore" .gitignore
 	;;
 "bun")
 	bun init -y
 	echo -e 'all:\n\tbun run start' >Makefile
 	jq '.scripts = { "start": "bun run index.ts" }' package.json |
 		sponge package.json
-	cp $IGNORE_DIR/Node.gitignore .gitignore
+	cp "${IGNORE_DIR}/Node.gitignore" .gitignore
 	;;
 "sh")
 	FILE="main.sh"
@@ -155,17 +113,17 @@ case $LANG in
 	;;
 "lua")
 	touch main.lua
-	cp $IGNORE_DIR/Lua.gitignore .gitignore
+	cp "${IGNORE_DIR}/Lua.gitignore" .gitignore
 	;;
 "rust")
 	touch main.rs
 	cargo init --name ${2:-sketch}
-	cp $IGNORE_DIR/Rust.gitignore .gitignore
+	cp "${IGNORE_DIR}/Rust.gitignore" .gitignore
 	;;
 "zig")
 	echo -e 'all:\n\tzig run main.zig\n\nbuild:\n\tzig build-exe main.zig' >Makefile
 	echo -e 'const std = @import("std");\n\npub fn main() !void {\n\tconst stdout = std.io.getStdOut().writer();\n\ttry stdout.print("Hello, {s}!\\n", .{"world"});\n}' >main.zig
-	cp $IGNORE_DIR/zig.gitignore .gitignore
+	cp "${IGNORE_DIR}/zig.gitignore" .gitignore
 	;;
 "d")
 	echo -e "$D_TEMPLATE" >main.d
@@ -177,18 +135,24 @@ case $LANG in
 	chmod +x ./main.ml
 	echo -e 'all:\n\t./main.ml' >Makefile
 	;;
+"perl")
+	echo -e "#!/usr/bin/env perl\n\nuse diagnostics;\nuse feature 'say';\n\n" >main.perl
+	chmod +x ./main.perl
+	echo -e 'all:\n\t./main.perl' >Makefile
+	;;
 esac
 
 echo "Directory: $DIR"
 
 BASHRC=$(mktemp)
 
-cat $HOME/.bashrc >$BASHRC
+cat "$HOME/.bashrc" >"$BASHRC"
 
-echo "nvim ." >>$BASHRC
+echo "nvim ." >>"$BASHRC"
 
-echo "PS1='\[\033[38;5;20m\]\[\033[48;5;11m\]sketch\[$(tput sgr0)\]\[\e[34m\] \w\[$(tput sgr0)\]\$ '" >>$BASHRC
+# shellcheck disable=SC2028
+echo "PS1='\[\033[38;5;20m\]\[\033[48;5;11m\]sketch\[$(tput sgr0)\]\[\e[34m\] \w\[$(tput sgr0)\]\$ '" >>"$BASHRC"
 
-tmux new -s sketch-$TMPNAME "bash --rcfile $BASHRC -i"
+tmux new -s "sketch-$TMPNAME" "bash --rcfile $BASHRC -i"
 
 exit 0
