Mon Aug  7 08:22:34 PM WEST 2023

diff --git a/files/home/bin/sketch b/files/home/bin/sketch
--- a/files/home/bin/sketch
+++ b/files/home/bin/sketch
@@ -4,7 +4,7 @@ LANG=$1
 
 function help() {
 	cat <<EOF
-Usage: sketch [go|js|ts|bun|sh|c|lua|rust] [NAME]
+Usage: sketch [go|js|ts|bun|sh|c|lua|rust|zig] [NAME]
 
 Creates a sketch project for a given language.
 The directory is created in $HOME/sketch with a random name.
@@ -21,9 +21,9 @@ fi
 LANG=$1
 NAME=$2
 
-if [[ ! "$LANG" =~ ^(go|js|ts|bun|sh|c|lua|rust)$ ]]; then
+if [[ ! "$LANG" =~ ^(go|js|ts|bun|sh|c|lua|rust|zig)$ ]]; then
 	help
-	echo "Invalid LANG: use go, js, ts, bun, c, lua or rust" >&2
+	echo "Invalid LANG: use go, js, ts, bun, c, lua, rust or zig" >&2
 	exit 1
 fi
 
@@ -138,6 +138,11 @@ case $LANG in
 	touch main.rs
 	cargo init --name ${2:-sketch}
 	cp $IGNORE_DIR/Rust.gitignore .gitignore
+	;;
+"zig")
+	echo -e 'all:\n\tzig run main.zig' >Makefile
+	echo -e 'const std = @import("std");\n\npub fn main() !void {\n\tconst stdout = std.io.getStdOut().writer();\n\ttry stdout.print("Hello, {s}!\\n", .{"world"});\n}' >main.zig
+	cp $IGNORE_DIR/zig.gitignore .gitignore
 	;;
 esac
 
